name: Test
run-name: Test ${{ github.ref_name }}
on:
  workflow_dispatch:
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Make
        run: .\Make.bat
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: paint.zip
          path: x64/Release/
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: paint.zip
          skip-decompress: true
      - name: Create
        run: gh release create "$GITHUB_REF_NAME" paint.zip
        env:
          GH_TOKEN: ${{ github.token }}
